from .auth import auth_router as auth
from .comment import comment_router as comment
from .comment_dislike import comment_dislike_router as comment_dislike
from .comment_like import comment_like_router as comment_like
from .dislike import dislike_router as dislike
from .followers import followers_router as followers
from .friends import friends_router as friends
from .history import history_router as history
from .like import like_router as like
from .message import message_router as message
from .media import media_router as media
from .private_media import private_media_router as private_media
from .role import role_router as role
from .user import user_router as user
from .websocket import websocket_router as websocket
from .favorites import favorites_router as favorites
from .history_views import history_views_router as history_views
from .user_blocks import user_blocks_router as user_blocks
from .pinned_message import pinned_message_router as pinned_message
